### ISSUE TITLE
Trouble running on macOS

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/Squidwarc#2]
`./Google\ Chrome.app/Contents/MacOS/Google\ Chrome --headless --disable-gpu --remote-debugging-port=9222`

...starts fine (per run-chrome.sh). In a second tab I try:

`./run-crawler.sh -c conf.json` from a fresh pull of the repo (db9e923c682a1fda79afea431cd8f988ec44e6f7) and receive the following output.

```bash
$ ./run-crawler.sh -c conf.json 
Running Crawl From Config File conf.json
Crawler Operating In page-only mode
Crawler Will Be Preserving 1 Seeds
Crawler Will Be Generating WARC Files Using the filenamified url
Crawler Generated WARCs Will Be Placed At /Users/machawk1/Downloads/Squidwarc
Crawler Is Connecting To Chrome On Host localhost
Crawler Is Connecting To Chrome On Port 9222
Crawler Will Be Waiting At Maximum For Navigation To Happen For 8s
Crawler Will Be Waiting After Page Load For 7s
Crawler Encountered A Random Error
  Error: getaddrinfo ENOTFOUND localhost localhost:9222
  
  - dns.js:28 errnoException
    dns.js:28:10
  
  - dns.js:76 GetAddrInfoReqWrap.onlookup [as oncomplete]
    dns.js:76:26
```

Google Chrome v59.0.3071.115 
Node v7.4.0
macOS 10.12.5

**Comment by machawk1** [comment]
I am able to replicate this issue in Node 9.1.0 on macOS 10.12.6. Running `node --harmony index.js -c conf.json` produces the same result.

**Comment by N0taN3rd** [comment]
@machawk1 I suspect that some delay should be added after starting chrome before launching the crawler.
The latter chrome versions might be delaying the start of the  internal remote debugging ws server 

I just pushed to the dev branch an auto-launcher that might help take care of any delay issues and will attempt to find the chrome binary automatically. 
But may require `executablePath=<path-to-chrome>`  to be added to config file if it does not find it correctly...

**Comment by machawk1** [comment]
Follow-up with new versions! Still having issues, unfortunately.

```
$  /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
Google Chrome 65.0.3325.181 
$ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --headless --disable-gpu --remote-debugging-port=9222
[0404/002533.562614:ERROR:gpu_process_transport_factory.cc(1019)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9222/devtools/browser/681b092e-cc06-4128-b41a-827ad539ed93
```

then wait awhile...then:

```
$ ./run-crawler.sh -c conf.json
Running Crawl From Config File conf.json
Crawler Operating In page-only mode
Crawler Will Be Preserving 1 Seeds
Crawler Will Be Generating WARC Files Using the filenamified url
Crawler Generated WARCs Will Be Placed At /private/tmp/Squidwarc
Crawler Is Connecting To Chrome On Host localhost
Crawler Is Connecting To Chrome On Port 9222
Crawler Will Be Waiting At Maximum For Navigation To Happen For 8s
Crawler Will Be Waiting After For 2 inflight requests
A Fatal Error Occurred
  TypeError: Promise.promisify is not a function
  
  - launcher.js:142 Function.findChromeDarwin
    /private/tmp/Squidwarc/lib/crawler/launcher.js:142:26
  
  - launcher.js:63 Function.findChrome
    /private/tmp/Squidwarc/lib/crawler/launcher.js:63:23
  
  - launcher.js:205 Function.launch
    /private/tmp/Squidwarc/lib/crawler/launcher.js:205:47
  
  - index.js:67 Crawler.init
    /private/tmp/Squidwarc/lib/crawler/index.js:67:37
  
  - configRunner.js:150 module.exports.R.compose
    /private/tmp/Squidwarc/lib/runners/configRunner.js:150:17
  
  

Please Inform The Maintainer Of This Project About It. Information In package.json
```

Squidwarc 83b42a7d1e4573c7268da8a01f6b085fe89f3d38 (current master), node 8.9.4, macOS 10.13.4.
